moduleroot/.gitignore.erb

`convert_report.txt` is generated during `pdk convert` and should not be committed.

(MAINT) Ignore `convert_report.txt`

---

config_defaults.yml

This PR is an attempt to bring the default configuration closer
to that of config_defaults in modulesync_configs.

(MODULES-6333) Add Puppet 5 to matrix for travis and appveyor

---

moduleroot/.travis.yml.erb

The previous code for this broke when branches:only was empty, as a result we've decided to make the key simply as 'branches' to avoid any confusion when reading in the config.

Fix empty config issue with .travis.yml.erb

---

moduleroot/appveyor.yml.erb

(https://bugs.ruby-lang.org/issues/11033)
This workaround is no longer required and should be removed.
The PDK is reverting the removal of this which was rolled out by modulesync as can be seen in this PR:
https://github.com/puppetlabs/puppetlabs-concat/commit/1587974bd7e1330a6ec329a54ccb97647f302c08

Removing openssl issue from appveyor config as is no longer required

---

README.md
config_defaults.yml
moduleroot/.yardopts.erb

This PR is to replace #22 , instead of adding the docs/ directory to the ignore files, we should be defaulting to the default output-dir of yardoc, and allow customization of the options in a .sync.yml.
Fixes #21 
Closes #22

(maint) Allows customization of .yardopts

---

config_defaults.yml

Removed the unnecessary Puppet 4 Ruby 2.4.1 run from .travis, and ensured appveyor is running tests on both 64 and 32 bit ruby with appropriate Puppet versions.

Additional changes to travis and appveyor

---

moduleroot_init/.project.erb

nature name is org.eclipse.. instead of com.eclipse...

Fix geppetto metadata to work with newer versions of eclipse

---

object_templates/provider_addon.erb
object_templates/provider_spec.erb

The Command API is scheduled to be removed. This is a simpler example
which also better explains what needs to happen in a provider.

(maint) avoid using Command API for new provider example

---

config_defaults.yml

This avoids accidental committing of this file after a `pdk update`.

Add `update_report.txt` to ignore files

---

moduleroot/Gemfile.erb

Adding an additional module to the Gemfile with something like:
```yaml
- gem: 'foo'
git: 'http://some.git.url/foo.git'
branch: 'bugfix'
```
causes an empty `ref` constraint to be added which breaks things. Looks like a copy & paste whoops.

Fix Gemfile template

---

README.md
config_defaults.yml
moduleroot/spec/spec_helper.rb.erb

Background: resource-api will check get values to see if they have been modified by canonicalize and will throw if Puppet strict is at :error level. 
This change ensures that tests are run at the highest level by default.

(PDK-511) Add strict checking for PDK unit test templates

---

moduleroot/Gemfile.erb

This replaces the old PR at https://github.com/puppetlabs/pdk-module-template/pull/62 and removes the legacy puppet checks and pins.
Closes https://github.com/puppetlabs/pdk-module-template/pull/62
Fixes #24

(PDK-706) Remove vulnerable puppet3 support dependencies

---

object_templates/provider.erb

The main Resource API is not required for loading a provider. Keep it
simple.

(maint) remove redundant require

---

moduleroot/spec/default_facts.yml.erb

Currently if you want extra facts that are structured it doesn't work as the value of the facts is just printed in ruby's `to_s` style. This fixes that.

Added ability to set structured extra facts

---

config_defaults.yml

Adding: BEAKER_PUPPET_COLLECTION=puppet5 to config_defaults.yml
Currently using the config_defaults.yml we are installing the puppet 5 gem. However when puppet-agent is actually installing using `beaker-puppet_install_helper` the value defaults to pc1 therefore it is installing puppet-agent  1.10.12-1. By setting this variable it installs puppet-agent.x86_64 0:5.5.1-1. I have tested these changes locally to ensure that they work.

(MODULES-6891) - Enable puppet 5 installation when using beaker-puppet_install_helper on travis

---

README.md
config_defaults.yml
moduleroot/.gitlab-ci.yml.erb

Added following improvements:
* `.gitlab-ci.yml` documentation added to the README.md
* Added code to `.gitlab-ci.yml.erb` to allow for users to override the defaults completely if they so choose.

More Gitlab CI improvements

---

moduleroot/.gitlab-ci.yml.erb

Changes in PR:
* Remove duplicate `global_variables` parsing code
* Cleanup end output
* Improve `custom_jobs` parsing to account for the fact that configuration options can be of type `String`, `Array`, `Hash`, and `Array in Hash`

Gitlab jobs parsing

---

config_defaults.yml

Prior to this commit, we ran `rake spec` instead of
`rake parallel_spec`.  Since every travis, appveyor, and
gitlab ci all provide at least 2 cores running in parallel
can reduce runtimes.
After this commit, we default to running parallel_spec.

Default to parallel specs in CI

---

config_defaults.yml

Prior to this commit, we duplicated work because release_checks
runs lint and spec tests which we do elsewhere in the .travis
matrix.
After this commit, we run just the tasks we are interested in.

(PDK-986) Only run parts of release_check task

---

README.md
moduleroot/.travis.yml.erb

Prior to this commit, the user could not remove the default included checks
with configuration.
After this commit, the user can specify default checks that should be removed
in the remove_includes configuration setting in .sync.yml
This allows for a .sync.yml like the following that replaces check=spec with
check=parallel_spec.
```
.travis.yml:
remove_includes:
- env: CHECK=spec
- env: PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
rvm:  2.1.9
includes:
- env: CHECK=parallel_spec
- env: PUPPET_GEM_VERSION="= 4.6.1" CHECK=parallel_spec
rvm: 2.1.9
- env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
rvm: 2.1.9
```

Add a remove_includes configuration option

---

README.md
config_defaults.yml
moduleroot/.travis.yml.erb

Updates the global configuration to use the beaker_puppet_collection to ensure we are testing on Puppet 5, also updated to the correct the puppet 4 run, in conjunction with the changes jearls introduced.
```
174 --- .travis.yml 2018-05-10 15:12:25.076285955 +0100
175 +++ .travis.yml.pdknew  2018-05-11 13:17:50.767612000 +0100
176 @@ -16,7 +16,9 @@
177  rvm:
178    - 2.4.1
179  env:
180 -  - PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
181 +  global:
182 +    - BEAKER_PUPPET_COLLECTION=puppet5
183 +    - PARALLEL_TEST_PROCESSORS=16
184  matrix:
185    fast_finish: true
186    include:
187 @@ -47,7 +49,7 @@
188      -
189        env: CHECK=spec
190      -
191 -      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
192 +      env: BEAKER_PUPPET_COLLECTION=pc1 CHECK=spec
193        rvm: 2.1.9
194 …
```

Addition of global_env section alongside configuration and docs update

---

README.md
moduleroot/.travis.yml.erb

Allow configuration of Travis `global` environment variables through the addition of a new `global_env` section in the travis configuration.
The existing `env` section is modified to add its environment variables to the `matrix` section of Travis's `env` settings (to keep identical behavior to the existing functionality).
See https://docs.travis-ci.com/user/environment-variables/#Global-Variables

(maint) Add global_env section to Travis configuration

---

config_defaults.yml

Currently, I'm working on adding Puppet Strings documentation to puppetlabs-mysql. When running rubocop on the module, after finishing a first pass, I got 3 warnings from the Style/Documentation cop that expects to see comments directly above Ruby modules. 
e.g.
```ruby
module Puppet::Parser::Functions
...
```
Since documentation for Strings will be going inside the @docs or passed to the desc method for any file inside 'lib/', we should disable this requirement for that directory. 
e.g.
```ruby
module Puppet::Parser::Functions
newfunction(:mysql_password, type: :rvalue, doc: <<-EOS
@summary
Hash a string as mysql's "PASSWORD()" function would do it
@param [String] password Plain text password.
@return [String] the mysql password hash from the clear text password.
EOS
) do |args|
...
end …
```

(maint) exclude lib/ directory from Style/Documentation cop

---

moduleroot/spec/spec_helper.rb.erb

Prior to this PR, the value for `spec_helper.rb` `hiera_config` was
not wrapped in quotes. It resulted in a failure when using the
`hiera_config` option as there is no `spec` object defined. This PR
adds quotes around the value in the template since it should always be a string.

Add quotes around the spec_helper's hiera_config

---

README.md
config_defaults.yml
moduleroot/Rakefile.erb

This adds an `extras` configuration option to allow for specifying arbitrary lines to the Rakefile. This is to enable adding additional requires and configuration options like
`MetadataJsonLint.options.strict_license`.

(PDK-967) Add an option to specify additional lines in Rakefile

---

config_defaults.yml

Prior to this PR, we spent quite a bit of time spinning up containers and installing software instead of actually checking anything.  
After this PR, we get quicker feedback and save resources on our various free CI providers by running more checks at the same time instead of in new containers.  
Example of Travis before ( 311 seconds ): 
Example of Travis after ( 66 seconds ): 
Specifically Travis notes it only takes 2.89 seconds to run all checks:
Example Gitlab CI before: 
Example Gitlab CI After:

(PDK-987) Save CI resources / reduce developer feedback time

---

moduleroot/spec/spec_helper.rb.erb
object_templates/provider_spec.erb

This should fix the acceptance test failures on PDK master

(FIXUP) Fix rubocop validation failure for new provider spec tests

---

.travis.yml
.travis/fixtures/new_provider_sync.yml
.travis/test_script.sh
moduleroot/spec/spec_helper.rb.erb

I can split this up into a couple PRs if we want, but this fixes the newly introduced "trailing newline" rubocop warning from #99 and significantly expands the Travis test suite for pdk-templates.
The new travis tests will generate a new module using pdk-templates from the PR, then generate a new instance of each time of module resource (class, provider, task, etc.), then run `pdk validate` and `pdk test unit` to make sure everything runs cleanly.
Steps 2 and 3 of the test suite continue to test that a module generated from the last release tag and from the current state of master can be converted to use the template from the PR.

Fix newline warning in updated spec_helper and improve pre-merge CI testing

---

config_defaults.yml

As of https://github.com/puppetlabs/puppet-module-gems/pull/65 puppet-blacksmith is carried in the puppet-module-gems, and does not need to be referenced here. This allows PDK users to override the pin with their own requirements.

(PDK-681) Remove puppet-blacksmith

---

config_defaults.yml

The cop excludes `spec/**/*` by default, and should do so going
forward, to avoid false positives, as there is no requirement for
module/class documentation in specs.
Example of this change in action:
```
david@davids:~/git/puppetlabs-panos$ pdk new provider panos_address
pdk (INFO): Creating '/home/david/git/puppetlabs-panos/lib/puppet/provider/panos_address/panos_address.rb' from template.
pdk (INFO): Creating '/home/david/git/puppetlabs-panos/lib/puppet/type/panos_address.rb' from template.
pdk (INFO): Creating '/home/david/git/puppetlabs-panos/spec/unit/puppet/provider/panos_address/panos_address_spec.rb' from template.
pdk (INFO): Creating '/home/david/git/puppetlabs-panos/spec/unit/puppet/type/panos_address_spec.rb' from template.
david@davids:~/git/puppetlabs-panos$ pdk validate …
```

revise Style/Documentation excludes

---

README.md
config_defaults.yml
moduleroot/.gitlab-ci.yml.erb

Extended the cache settings that @npwalker added to make the setting configurable and move the default settings from the template into the `config_defaults.yml` file

Make gitlab cache configurable

---

README.md

Prior to this PR, there was no mention of the knockout_prefix
implemented in PDK-949. This PR adds a note about using the `---`
prefix in the `.sync.yml` to knock out values.

(maint) Add a note about the knockout_prefix

---

config_defaults.yml

This aligns with the ruby version provided by the pdk.

(PDK-1066) Use ruby 2.4.4 with travis

---

README.md
config_defaults.yml
moduleroot/.travis.yml.erb

Currently, there are two branches are hardcoded to be included in the `.travis.yml`. This PR moves those branches into the`config_defaults.yml` and adds an option to remove those default
branches. It also includes an option to specify travis's `except` branch option.
With this, you can now have a more complex configuration for specifying which branches should be included in the `.travis.yml`. Below are a few examples. 
Only use an `except`:
~~~
.travis.yml:
remove_branches:
- master
- /^v\d/
branches_except:
- /^mergeup.*$/
~~~
Results in
~~~
branches:
except:
- /^mergeup.*$/
~~~
Remove one of the default branches and add another branch.
~~~
.travis.yml
remove_branches:
- /^v\d/
branches:
- development
~~~
Results in
~~~
branches:
only:
- master
- development
~~~

Add option to specify except branches in .travis.yml

---

moduleroot/.travis.yml.erb

I left some extra spaces in #97. This PR removes those unnecessary spaces from each branch.

(maint) Remove extra white space in .travis.yml branches

---

moduleroot/.gitlab-ci.yml.erb

Several beaker-related fixes from #104

---

moduleroot/.gitlab-ci.yml.erb

Per conversation on slack w/ @dhollinger and @DavidS -
https://puppetcommunity.slack.com/archives/C113FRBRU/p1533844991000226
https://puppetcommunity.slack.com/archives/C113FRBRU/p1533845132000355
https://puppetcommunity.slack.com/archives/C113FRBRU/p1533845264000395
I think this will suffice, to drop any "default" or "custom" checks that match spec into the unit stage.

fixing stage job pinning so that spec jobs fall into unit stage

---

config_defaults.yml

remove concat_basedir from default-facts

---

config_defaults.yml

This PR adds test matrices to test Puppet 6 on ruby 2.5.0. I have ran test on iis by rolling out these template changes and I can confirm they passed with no failures.

(FM-7398) - Update unit tests for Appveyor to test on Puppet 6 and ruby 2.5.0

---

object_templates/provider_spec.erb

The delete function does not take a `should` argument. This commit removes the wrong documentation in the spec.

Remove wrong argument from spec

---

moduleroot/spec/spec_helper.rb.erb

Since we already check whether the file is there, a `LoadError` will only occur when there is a error in the `spec_helper_local`. A warning is not appropriate in this case, as it will usually only mean that there is another (now obscured) error later in the test run.

Fail on broken spec_helper_local

---

config_defaults.yml

For consistent behaviour with erb templates.

(maint) Prefer LF over CRLF line endings for .epp files

---

moduleroot/spec/spec_helper.rb.erb

If the file exists but has been truncated, silently skip it as if it does not exist.
If the file exists but doesn't contain valid YAML, add a warning to the RSpec output and attempt to continue running the tests.
```
semirhage :0: pdk/foo (git:master → origin ↑5 ?:1!)$ ../bin/pdk test unit
pdk (INFO): Using Ruby 2.4.4
pdk (INFO): Using Puppet 6.0.3
[✔] Preparing to run the unit tests.
[✔] Running unit tests.
WARNING: Unable to load /home/tsharpe/code/puppetlabs/pdk/foo/spec/default_facts.yml: no implicit conversion of String into Hash
Evaluated 9 tests in 0.311514725 seconds: 0 failures, 0 pending.
```

(PDK-1191) Gracefully handle default_fact YAML load errors

---

config_defaults.yml
moduleroot/appveyor.yml.erb

The problem is described in #154.  This commit ensures only master and pr branches get build.

(GH-154) Fix appveyor double build

---

moduleroot/spec/default_facts.yml.erb

This fact has been unused since puppetlabs-concat 2.0 so it's safe to remove.

Remove concat_basedir fact

---

moduleroot/spec/spec_helper.rb.erb

If there is a top level module with same name as a type which gets loaded before the type gets defined.
This will trigger a false positive on the `last_module.const_defined?` check causing an `uninitialized constant` error.
This change will no longer do a recursive check and only care about the local namespace this way avoiding the false positive.

(PDK-1210) setting inherited const_defined lookup to false

---

README.md
moduleroot/.travis.yml.erb

Hi, this enables you to specify `stages` section within `.travis.yml`. Using stages is a way to group and run jobs in parallel in each stage, but sequential one stage after another. This way you don't need to run all expensive spec and beaker test cases if some cheap static code analysis, e.g. lint or rubocop was not successful.
May have a look on this example:
- [rtib/puppet-static_custom_facts integration](https://github.com/rtib/puppet-static_custom_facts/tree/integration) branch
- and its according [Travis-CI Build](https://travis-ci.org/rtib/puppet-static_custom_facts/builds/459059905)

add support for travis stages

---

config_defaults.yml

Trim down the module builds to just what they need to run on a production puppet master.

(PDK-957) Exclude all development files from module builds

---

config_defaults.yml
moduleroot/.gitlab-ci.yml.erb
moduleroot/.travis.yml.erb

After the upgrade of [rubygems-update](https://rubygems.org/gems/rubygems-update/versions/3.0.0) the travis and gitlab-ci jobs are broken with
```bash
Updating rubygems-update
Fetching: rubygems-update-3.0.0.gem (100%)
ERROR:  Error installing rubygems-update:
rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (Errno::ENOENT)
No such file or directory @ dir_chdir - /usr/local/bundle/gems/rubygems-update-2.6.6
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
```
This patch has fixed it with the installation of the latest compatible version.

Fix rubygems-update for ruby older than 2.3 for travis and gitlab-ci

---

config_defaults.yml
moduleroot/.travis.yml.erb

New version of Bundler does not support ruby versions older than 2.3 or RubyGem versions older than 3.0.0

(FM-7659) - Fix to pin Bundler for Puppet 4 Testing

---

config_defaults.yml

This updates the generated Gemfile to avoid it trying to resolve JSON to 2.1.0 on Ruby 2.4.5 (and future 2.4.x releases of Ruby). It's possible we might have to tweak the ranges if Ruby embeds a different JSON version in a future release but that seems more rare than us just bumping the Ruby patch version.

(MAINT) Update JSON pinning to cover Ruby 2.4.5 and future Rubies

---

moduleroot/spec/spec_helper.rb.erb

Any module that has unit tests for bolt plans is likely to need these
filters in place. If they are not in the default templates then hand
crafting of these files will have to be done. If it is not, then nothing
can pass Appveyor checks because linting will fail, and any bolt unit
tests will also fail, even though they should have been filtered out and
not run at all.

(WIN-251) Add Bolt Filters to template files

---

README.md
config_defaults.yml
moduleroot/spec/spec_helper.rb.erb

Two options are added:
- coverage_report: Defaults to false
- minimum_code_coverage_percentage: Defaults to 0
Wasn't sure how to test this since all the things I could find for using a custom template only allowed pulling from master...

Add options for rspec-puppet coverage reports

---

README.md
moduleroot/.puppet-lint.rc.erb
moduleroot/Rakefile.erb

Hello. Currently, `Rakefile` options could only disable some checks but it's impossible to affect other options like `fail_on_warnings`.
This PR implements the way to do it

Allow more control over puppet-lint options

---

README.md

clarify that `moduleroot_init` is only used on creation of a new module

update short description for `moduleroot_init`

---

config_defaults.yml

Changes to gitlab ci configuration to run static analysis against Puppet 6 and spec test against Puppet 6. Also changes the Puppet 5 job to run against the latest Puppet 5, and removes Puppet 4 from the matrix.

(PDK-1277) Update gitlab-ci config to test against latest Puppets.

---

moduleroot/spec/spec_helper.rb.erb

When mocking facts, its extremely useful to be able to use aliases in the default fact files:
```yaml
---
ipaddress: &ipaddress '192.168.1.13'
macaddress: &mac '13:13:13:13:13:13'
networking:
ip: *ipaddress
mac: *mac
netmask: &netmask '255.255.255.0'
network: &network '192.168.1.0'
primary: 'eth0'
dhcp: 192.168.1.1
interfaces:
'eth0':
mac: *mac
mtu: 1500
ip: *ipaddress
netmask: *netmask
network: *network
bindings:
- address: *ipaddress
netmask: *netmask
network: *network
```

(PDK-1297) Allow the use of aliases in default fact files.

---

config_defaults.yml

This is used by direnv and is a common tool for specifying environment variables for local development.

ignore .envrc

---

README.md
config_defaults.yml
moduleroot/Rakefile.erb

When using [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) together with [puppet-blacksmith](https://github.com/voxpupuli/puppet-blacksmith), there is a discrepancy between changelog "future_release" property, which we fill in the version number from metadata.json as is, and the default "tag_pattern" used by puppet-blacksmith to tag the current version, resulting in broken compare links and wrong version tag references in the changelog.
This change introduce the config parameter "changelog_version_tag_pattern" to allow templating the returnVal of changelog_future_release function of Rakefile, and sets the default value to align with blacksmith's "tag_pattern". When using rake tasks ```changelog``` and then ```module:tag``` the …

configurable tag_pattern for changelog

---

README.md

(GH-217) Add ability to use Rakefile.local

---

config_defaults.yml

This aligns with PDK already ignoring the Rakefile.

(GH-217) PDK to ignore rakelib directory

---

config_defaults.yml

The latest Puppet 5 release is 5.5.10 which uses Ruby 2.4.5.
https://puppet.com/docs/puppet/5.5/about_agent.html

(GH-215) Use the correct ruby version for testing Puppet 5

---

config_defaults.yml

Latest Puppet 6 release is 6.3.0 and uses Ruby 2.5.3
https://puppet.com/docs/puppet/6.3/about_agent.html

(GH-203) Use the correct ruby version for testing Puppet 6

---

config_defaults.yml

Hi there, I'd propose some changes to travis-ci defaults. Main goal is to leverage build stages by default. Along with some maintenance and bug fixing the main changes in this PR are:
* (improvement) define stages: static, spec, beaker, deploy
* (feature) deploy stage is limited to version tag
* (maintenance) remove unnecessary global env
* (bugfix) add bundler_args "--with system_tests" to docker_defaults
* ~~(improvement) split static code analysis jobs to multiple jobs on static stage~~
* (improvement) move spec test jobs to spec stage
* (maintenance) replace default spec job with explicit Puppet 6 job
* (maintenance) order spec test jobs by major version
* (improvement) introduce deploy job on deploy stage
I've been using such a setup for some time now and would like to push them …

improve travis-ci defaults to leverage build stages

---

config_defaults.yml

This reverts commit 8712ac67a4a4132b4a9473042e4f2da930ca9280.
The `.vscode` directory is used to store workspace level overrides, including testing, formatting etc.  It is _designed_ to be checked into repos and should not be ignored by default.
---
The .vscode directory is not required when packaging a module for the forge.
This commit adds this directory to the list of default PDK ignores.

Revert "Add Visual Studio Code to gitignote (.vscode/)"

---

moduleroot/.gitlab-ci.yml.erb

Previously custom configs of the same key were not overriding existing keys.

(MAINT) Ensure .gitlab-ci.yaml configs are merged in the correct order

---

README.md
config_defaults.yml
moduleroot/.travis.yml.erb

Without this patch, the TravisCI configuration will be broken and add a
deployment section with the incorrect password and without documentation
to explain how to do deploys correctly.

(GH-223) .travis.yml does not deploy by default

---

moduleroot/spec/spec_helper.rb.erb

My commit hooks complain that the ensure_module_defined method in
spec/spec_helper.rb is undocumented. This commit provides the minimal
documentation strings that satisfies YARD. Better documentation is
always welcome :)

Add documentation to satisfy YARD

---

moduleroot_init/README.md.erb

When generated, the README.md will have a leading newline.

Remove leading whitespace from README template

---

moduleroot/Rakefile.erb

It is not safe to presume the module name matches the repo name in GitHub, etc.
Fixes #230

Read the project name from `source` instead of `name`

---

config_defaults.yml
moduleroot/.rubocop.yml.erb

Also disables rubocop-i18n cops by default which is both a sane default and maintains consistency with previous behavior. (They weren't being required before so they weren't running.)
The i18n cops can be enabled on a per-module basis using `.sync.yml`.
Here is the diff of applying this template change to a module:
```diff
--- .rubocop.yml        2019-05-02 11:32:53.282703881 -0700
+++ .rubocop.yml.pdknew 2019-05-02 11:33:06.361388000 -0700
@@ -1,5 +1,7 @@
---
-require: rubocop-rspec
+require:
+- rubocop-rspec
+- rubocop-i18n
AllCops:
DisplayCopNames: true
TargetRubyVersion: '2.1'
@@ -19,6 +21,8 @@
Metrics/LineLength:
Description: People have wide screens, use them.
Max: 200
+GetText:
+  Enabled: false
GetText/DecorateString:
Description: We don't want to decorate test output.
Exclude: …
```

(MAINT) Require rubocop-i18n as part of default rubocop config

---

config_defaults.yml

Should resolve weird bundler resolution edge-case with Puppet 6.5.0
(Was causing puppet-module-posix-dev to resolve to 0.0.8 in order to satisfy newer `fast_gettext`)

(MAINT) Add minimum version pinning to default puppet-module-* gem deps

---

NOTICE

When using the templates in their intended form through the PDK we do not want to add legal burden on the users. To clarify this, we note here that the rendering of the modules through the PDK already leaves enough traces (e.g. the `template-url` in `metadata.json`) that the conditions of section 4 (Redistribution) are met without any further action on the Licensor's side.
I'll take this opportunity to also point out that the files rendered from the pdk-templates will remain Derivative Works of pdk-templates, e.g. for the purpose of section 3 (Grant of Patent License). Thanks to the specifics of the Apache 2.0 license this clearly does not extend to the main content of  a module, either through "remaining separable" from the templated files, or through the fact that the templated result …

Clarify license when using the templates

---

object_templates/transport_device.erb
object_templates/transport_type.erb

This missing file was an oversight from #251. It is required for a functioning
transport with puppet.

(FM-8081) Add DeviceShim template too

---

config_defaults.yml

The change ensures that the spec directory along with child directories
are excluded from this rubocop rule.

(maint) Exclude spec folder for GetText/DecorateString

---

moduleroot/.travis.yml.erb

The xenial dist includes ruby 2.4 and 2.5 by default so users can avoid spending 20-30 seconds, per job, installing these versions of ruby just by changing the dist.

Update travis dist to xenial by default

---

README.md
moduleroot/.gitlab-ci.yml.erb

I have a use case where I need to do additional setup steps for the GitLab pipeline to work (add ca-certificates to allow communication through the proxy). This PR adds the ability to add custom steps in your `.sync.yml` to the before_script in the GitLab CI pipeline.
closes https://github.com/puppetlabs/pdk-templates/issues/134

(PDK-1351) Enable custom steps in before_script for GitLab CI

---

.travis.yml
.travis/install_pdk.sh

The recently introduced PDK analytics feature prompts for user
consent on first invocation which is preventing the Travis CI
job from completing successfully on those PDK builds. This
will ensure that PDK analytics are always disabled.

Disable PDK analytics in Travis CI

---

moduleroot/spec/spec_helper.rb.erb

Prior to this commit, facts provided via default facts would
be ignored if the fact was provided by facterdb.  Which is the
case for any of the standard facts.
After this commit, facts provided via default facts will
override what is provided by facterdb.

Override facterdb with default_facts

---

README.md
moduleroot/.puppet-lint.rc.erb
moduleroot/Rakefile.erb

Add 'linter_fail_on_warnings' option to configure puppet lint
to return a failure code for all warnings as well as failure
conditions.

(PDK-1417) Allow linter failure on warnings

---

README.md
moduleroot/Gemfile.erb

Add the ability to specify a per-gem source where needed.

(PDK-1416) Support Gemfile source option

---

config_defaults.yml
moduleroot/spec/default_facts.yml.erb

Puppet 6.9.0 now sets a serverip6 fact which is set to the ipaddress6
fact value on the compiling host.
https://github.com/puppetlabs/puppet/commit/48f720a68d9a2903b9ea71561f87af16136d76f6

(maint) Add default ipaddress6 fact

---

.gitignore
Gemfile
rubocop/defaults-0.49.1.yml
rubocop/profile_builder.rb

Previously the rubocop profile builder had not been updated for the i18n rubocop
rules.  This commit:
* Updates the script to work on Windows
* Updates the script for running in the `/rubocop/` directory
* Adds the i18n rubocop gem in the Gemfile so it can be profiled
* Updates the 0.49.1 rubocop profile with the GetText/* rules

(PDK-1439) Ignore GetText rubocop rules for the off profile

---

.gitignore

~ is a common suffix for editor temporary or editor backup files, for editors that aren't vim.

Ignore *~ files

---

object_templates/transport.erb
object_templates/transport_spec.erb

Unwraps the password value in the transport template when used. Also updated the specs for the transport to mock the password with `Sensitive` data type objects.
```
$ pdk test unit --verbose
pdk (INFO): Using Ruby 2.4.7
pdk (INFO): Using Puppet 6.10.1
[✔] Preparing to run the unit tests.
/home/tsharpe/.rbenv/versions/2.4.7/bin/ruby -I/home/tsharpe/.pdk/cache/ruby/2.4.0/gems/rspec-core-3.9.0/lib:/home/tsharpe/.pdk/cache/ruby/2.4.0/gems/rspec-support-3.9.0/lib /home/tsharpe/.pdk/cache/ruby/2.4.0/gems/rspec-core-3.9.0/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb --format documentation
Run options: exclude {:bolt=>true}
Puppet::Transport::Bar
initialize(context, connection_info)
is expected not to raise …
```

(#283) Unwrap password in transport object template

---

README.md
config_defaults.yml
moduleroot/Gemfile.erb
moduleroot/appveyor.yml.erb

Previously if a module wanted to use Litmus for acceptance testing it could not
be managed by PDK.  This commit adds the requried boiler plate to the appveyor
configuration file, which then allows Litmus based tasks to be executed.
---
Previously if a module used Litmus for acceptance testing it was possible that
Bundler would choose Development metagems that did not include Litmus which
would then cause CI, or local testing failures.  This commit:
* Adds a `use_litmus` setting to the Gemfile
* When the use_litmus setting is set to true, the Gemfile template is modified
so that the development gems will be select a version that contains the
litmus gem
Note that this munging is used because it is not possible to add the complex
logic into the config_defaults file. Nor is it possible to …

(PDK-1500) Update Appveyor and Gemfile templates for Litmus

---

moduleroot/appveyor.yml.erb

Previously in commit 0e670e6fbc Litmus support was added to the appveyor config
file, however it was missing the same debug output as non-litmus tests.  This
commit uses the same test commands and realigns the YAML indentation.

(PDK-1500) Update Limtus configuration in Appveyor

---

README.md
config_defaults.yml
moduleroot/.travis.yml.erb

Previously the Travis configuration was setup in a way that made it difficult
to stop auto-forge deployment or use a different tagging system.  This commit
makes the auto deployment of modules optional (opt-out), and allow users to
configure their own tag regex if needed.
This commit preserves the current template defaults, thereby making this a non
breaking change.

(maint) Make module deployment in Travis opt-out

---

README.md
config_defaults.yml
moduleroot/.gitlab-ci.yml.erb

Currently the `.gitlab-ci.yml` template always assumes you are using Bundler, and you will always get this section in the file:
```
before_script:
- bundle -v
- rm Gemfile.lock || true
- gem update --system $RUBYGEMS_VERSION
- gem --version
- bundle -v
- bundle install
```
If you need to do a customised Bundler install, or not use bundler at all (eg: Docker image that's already configured), then this section needs to be removed.
I've added a boolean `default_before_script` to the config of the `.gitlab-ci.yml` file.  Here is an example of how it is used in `.sync.yml`:
```
.gitlab-ci.yml:
override: true
custom:
default_before_script: false
custom_jobs:
pdk:
script:
- pdk test unit --parallel
tags:
- shell_c7
```
If the boolean is not set, the default behaviour remains the same: the …

Boolean to remove the before_script section in .gitlab-ci.yml

---

moduleroot/.gitlab-ci.yml.erb

Use `YAML.dump` to generate the custom job YAML rather than trying to
manually walk the hash and render it.
Given the `.sync.yml` in #290:
```
---
.gitlab-ci.yml:
override: true
custom:
custom_stages:
- 'unit'
custom_jobs:
testjob:
stage: unit
image: ruby:2.5.3
script:
- 'echo 1'
artifacts:
reports:
junit: 'tmp/*.xml'
```
The rendered `.gitlab-ci.yml` is now:
```
---
stages:
- unit
before_script:
- bundle -v
- rm Gemfile.lock || true
- gem update --system $RUBYGEMS_VERSION
- gem --version
- bundle -v
- bundle install
testjob:
stage: unit
image: ruby:2.5.3
script:
- echo 1
artifacts:
reports:
junit: tmp/*.xml
```
Fixes #290

(#290) Do not manually generate YAML in .gitlab-ci.yml

---

moduleroot/.gitlab-ci.yml.erb
moduleroot/.travis.yml.erb

The `bundle update --system` was originally added as a response to
https://github.com/travis-ci/travis-ci/issues/3531#issuecomment-88311203 .
See https://github.com/puppetlabs/puppetlabs-motd/blob/a56235c5fe6a7514ad3e13e9be840af76c997e5d/.travis.yml#L7-L9 .
Then later it was reinserted in https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f
Since a few hours, this has started breaking tests because of a change in
bundler: https://travis-ci.org/puppetlabs/puppetlabs-apache/jobs/625596052
```
$ gem update --system $RUBYGEMS_VERSION
Updating rubygems-update
Fetching: rubygems-update-3.1.1.gem (100%)
Successfully installed rubygems-update-3.1.1
Installing RubyGems 3.1.1
Successfully built RubyGem
Name: bundler
Version: 2.1.0
File: bundler-2.1.0.gem …
```

Update travis and gitlab to run `gem update --system` only when requested

---

object_templates/transport_device.erb

This always has been a class (see https://github.com/puppetlabs/puppet/blob/master/lib/puppet/util/network_device.rb). Somehow the network_device.rb is getting pulled in now leading to 
```
Error: Can't load transport for node: NetworkDevice is not a module
```

Change NetworkDevice module to class

---

moduleroot/.gitlab-ci.yml.erb
moduleroot/.travis.yml.erb

Latest rubygems isn't correctly detecting TTYs on some CI platforms like
TravisCI and presents a prompt to overwrite binstubs that causes test
execution to fail (https://github.com/rubygems/rubygems/pull/3040). As
a workaround, we can pipe `yes` to `rubygems update --system` to
automatically confirm the prompt.

(maint) Fix non-interactive rubygems update

---

moduleroot/.gitlab-ci.yml.erb
moduleroot/.travis.yml.erb

If pipefail is set in the runner's shell, then it will fail as 'yes' will receive
SIGPIPE and exit with code 141 which will fail the job. The workaround ignores
the return code of 'yes' whether or not pipefail is set
#303 introduced the problematic yes pipe.

Fix rubygems update in runners with pipefail set

---

README.md
config_defaults.yml
moduleroot/Gemfile.erb

The 0.4 series has been in use in the Content team for a while now and
has proven to be stable.

Update puppet-module gems to current version

---

README.md
config_defaults.yml
moduleroot/.travis.yml.erb

add new variable to _use_litmus_ to configure travis for litmus modules
old functionality is not affected
How to use: in `.sync.yml` file the following code
```
-
before_script: ["bundle exec rake 'litmus:provision_list[travis_el]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
bundler_args: 
dist: trusty
env: PLATFORMS=travis_el_puppet5
rvm: 2.5.1
script: ["bundle exec rake litmus:acceptance:parallel"]
services: docker
stage: acceptance
sudo: required
```
can be replaced with this code:
```
use_litmus: true
```
```
by default:
use_litmus: false
litmus:
provision_list: [travis_deb, travis_el]
puppet_collection: [puppet5, puppet6]
rvm: '2.5.3'
install_wget: no
```
-
before_script: ["bundle exec rake 'litmus:provision_list[<%= …

FM-8769 - add use_litmus to configure to use Litmus for acceptance testing jobs

---

README.md
moduleroot/Rakefile.erb

- Added github_site for remote server
- Added github_endpoint for remote server
- Added gitlab for preparation of gitlab support added in (https://github.com/github-changelog-generator/github-changelog-generator/pull/657)
These settings will not be added by default. Only if added to `.sync.yml`
They allow for GitHub Enterprise and Gitlab options down the road.

Changes for github_changelog_generator Raketask

---

README.md
moduleroot/spec/spec_helper.rb.erb

Currently, the pdk is pinned to facterdb 0.8.2 which doesn't auto-detect facter versions as well as we could wish, but users can override the facter version. This new parameter in the sync file allows the setting to persist across a `pdk update`.

Add `default_facter_version` parameter to `.sync.yml`

---

moduleroot/.travis.yml.erb

Travis-CI's build config validation is complaining a couple of issues with the generated `.travis.yml`.
I've tried to gratify those claims with these changes. For now, Travis seems to be satisfied with.

resolve some Travis-CI build config validation issues

---

moduleroot_init/hiera.yaml.erb

The `os.name` fact is more specific than the `os.family` fact and so it
should be higher in the hierarchy.

(PDK-1609) Prefer os.name over os.family in hiera.yaml

---

.travis.yml
README.md
config_defaults.yml

Amongst other things, this avoids a ruby segfault with concurrent-ruby-1.1.6 (see https://github.com/ruby-concurrency/concurrent-ruby/issues/849)

Update to latest ruby version supported by the agent

---

README.md
config_defaults.yml
moduleroot/Gemfile.erb

Keen observers may note that only one template is affected by this change in contradiction to the description of the `common` namespace introduced here. In a future release I plan to add the ability to disable legacy facts during rspec-puppet catalogue testing which will also be controlled by this setting.

(PDK-1591) Add option to enable legacy_facts puppet-lint plugin

---

README.md
config_defaults.yml
moduleroot/spec/spec_helper.rb.erb

Currently due to https://github.com/puppetlabs/puppetlabs_spec_helper/blob/070ecb79a63cb8fa10f46532c413c055e2697682/lib/puppetlabs_spec_helper/module_spec_helper.rb#L71 the default of `false` is overridden. 
This is to allow you to set the value back to `false` and avoid having to use `STRICT_VARIABLES=no` on a unit test run.
@DavidS

Added strict_variables config setting

---

config_defaults.yml
rubocop/defaults-0.49.1.yml

The `Style/BracesAroundHashParameters` cop would flag "redundant" uses
of braces to create hashes in Ruby method arguments. Ruby 2.7 requires
these braces to disambiguate hash literals from keyword arguments and
will issue warnings. The cop has been removed from RuboCop v0.80.0.
See: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
See: https://github.com/rubocop-hq/rubocop/pull/7643

Disable RuboCop Style/BracesAroundHashParameters

---

README.md
config_defaults.yml
moduleroot/.travis.yml.erb

An update to the travis template to allow you to make a more complex test environment. An example of what can be given is:
```
litmus:
provision_list:
- travis_deb
- travis_el6
- travis_el7
- ---travis_el
complex:
- collection:
puppet_collection:
- puppet6
provision_list:
- travis_ub_6
- collection:
puppet_collection:
- puppet5
provision_list:
- travis_ub_5
```

(IAC-805) - Update to Travis template

---

moduleroot/Rakefile.erb

* Use a release version of github-changelog-generator. The gem has had several upstream releases recently fixing most of the issues we encountered. Most importantly the pdk default configuration for labels now works out of the box.
* Start aligning with github's default labels to reduce the effort for publishing a new module
* Add support for github's default labels "bug" and "documentation"
* List github's default labels first in the `configure_sections`

Update changelog generation: default github labels and new upstream

---

config_defaults.yml

Despite https://github.com/puppetlabs/pdk-templates/pull/329 (which
aimed to disable this cop), in the last round of module updates, it is
set as `enabled: true` in all puppetlabs modules.
Removing the line from the cleanup_cops seems to fix this.

Fix disabling of BracesAroundHashParameters

---

README.md
moduleroot/appveyor.yml.erb

Add a remove_includes configuration option
Prior to this commit, the user could not remove the default included checks in appveyor file.
After this commit, the user can specify default checks that should be removed
in the remove_includes configuration setting in .sync.yml
This allows for a .sync.yml like the following that replaces static check from 24 to 25
```appveyor.yml:
use_litmus: true
spec_type: spec
remove_includes:
-
RUBY_VERSION: 24-x64
CHECK: syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
matrix_extras:
-
RUBY_VERSION: 25-x64
CHECK: syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop```

(IAC-940) Add a remove_includes configuration option

---

moduleroot/.gitlab-ci.yml.erb

According to https://docs.gitlab.com/ee/ci/yaml/README.html#globally-defined-image-services-cache-before_script-after_script:
> Defining `image`, `services`, `cache`, `before_script`, and `after_script` globally is deprecated. Support could be removed from a future release.
This change moves `image`, `cache`, and `before_script` to the top-level `default` key instead.
Fixes #350.

(#350) Update deprecated globals

---

moduleroot/.gitlab-ci.yml.erb

This would incorporate global variables in the job level variables.
This could probably be even turned into some sort of YAML anchor instead

Add global_variables key for GitLab CI to set defaults that can be overridden by jobs

---

README.md
config_defaults.yml
moduleroot/.gitpod.Dockerfile
moduleroot/.gitpod.yml

* This adds initial support for gitpod puppet development.  Any user
who opens the module in gitpod would automatically
stand up a PDK and puppet development environment.
While this is a first stab at this file I expect further customizations
to follow and allow the user to utilize the sync or config_defaults
to tweak their own unique gitpod.
I decided to leave the clickable banner that normally goes in the readme out of this changeset as I don't know
what the user's gitpod link would actually be.  I am sure a config variable might help with this but decided to KISS.
An example of this setup can be viewed here by clicking this link: [![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod)](https://gitpod.io/#https://gitlab.com/nwops/control-repo.git)

Add gitpod support for puppet modules

---

moduleroot/.github/workflows/nightly.yml.erb
moduleroot/.github/workflows/pr_test.yml.erb

Without an inventory this would never be able to create a
correct tear_down call. Instead it is causing a second error
that is confusing the github actions log viewer. This change
avoids running the `litmus:tear_down` rake task when provisioning
has failed.

Avoid second failure if provision doesn't create inventory

---

moduleroot/.github/workflows/nightly.yml.erb
moduleroot/.github/workflows/pr_test.yml.erb

Thanks to https://github.com/kvrhdn/gha-buildevents/pull/15 being merged
and released, we can now use the upstream version again.
This also adjusts some of the names for easier parsing.
See https://github.com/puppetlabs/puppetlabs-testing/pull/321 for smoke test.

Update honeycomb buildevents tracking

---

moduleroot/.github/workflows/nightly.yml.erb
moduleroot/.github/workflows/pr_test.yml.erb

Rely on litmus' provisioning retry loop instead

github actions: Don't retry at the workflow level

---

moduleroot/.rubocop.yml.erb

2.1 has some changes to hash syntax.
using 2.1 shows false positives

(fix) Set rubocop ruby version to 2.4

---

config_defaults.yml

When puppet7 becomes available and the linting check installs puppet7, it will fail as Puppet7 only supports ruby 2.5+
I have tested the template change locally and can confirm it only changes the Ruby version for appveyor. I have also put up a PR with the change to confirm it works as expected. PR can be found here: https://github.com/puppetlabs/puppetlabs-acl/pull/223

(maint) Update Ruby version for Appveyor linting checks

---

moduleroot/.github/workflows/nightly.yml.erb
moduleroot/.github/workflows/pr_test.yml.erb

> Malicious code can be inserted into any GitHub action, even those which are tagged.
-- https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
This is mitigated through using https://github.com/mheap/pin-github-action to update non github-provided actions to use a full SHA instead of relying on mutable tags or branch names.

(SEC-250) Pin non-github provided actions to a specific SHA

---

moduleroot/.rubocop.yml.erb
object_templates/provider_type.erb

Note how the original `Include` value causes no files to be scanned.
See [rubocop docs](https://docs.rubocop.org/rubocop/configuration.html#includingexcluding-files) for background.
```
david@zion:~/git/pdksync/modules_pdksync/provision (main)$ grep -A5 AllCops .rubocop.yml
AllCops:
DisplayCopNames: true
TargetRubyVersion: '2.4'
Include:
- "./**/*.rb"
Exclude:
david@zion:~/git/pdksync/modules_pdksync/provision (main)$ bundle exec rake rubocop:auto_correct
Running RuboCop...
Inspecting 0 files
0 files inspected, no offenses detected
david@zion:~/git/pdksync/modules_pdksync/provision (main)$ grep -A5 AllCops .rubocop.yml
AllCops:
DisplayCopNames: true
TargetRubyVersion: '2.4'
Include:
- "**/*.rb" # changed this
Exclude:
david@zion:~/git/pdksync/modules_pdksync/provision (main)$ bundle exec …
```

Fix Include syntax for new rubocop

---

config_defaults.yml
rubocop/cleanup_cops.yml

The hash alignment does not work satifactorily and produces a lot of unsightly artifacts.

Remove Layout/HashAlignment from the default cleanup cops

---

config_defaults.yml
moduleroot/Gemfile.erb

The way bundler resolves the puppet_litmus dependencies is currently
preventing dependency resolution when Puppet version is less than
6.11.0. This updates the PDK-generated Gemfile to fall back to the
pre-1.0 releases of the `puppet-module-*-system` gems when the Puppet
version is less than 6.11.0.

(MAINT) Fix bundler resolution issues for older puppet versions

---

config_defaults.yml

Following @DavidS's suggestion, I think this is simpler than trying to resolve all the dependency conflicts...

(MAINT) Remove puppet-module-system gems for older Puppet versions

---

README.md
moduleroot/.github/workflows/nightly.yml.erb
moduleroot/.github/workflows/pr_test.yml.erb

As explained in [Use GitHub actions at your own risk](https://julienrenaux.fr/2019/12/20/github-actions-security-risk/),
when running github actions from outside the organisation,
there is a risk that symbolic references get taken over by malicious actors.
Similar things happened before in other ecosystems and other packaging registries.
The blog post goes on to suggest pinning to specific SHAs and provides some tooling to do so.
The downsides for us are that the tooling doesn't work well with our ERB templating,
and the additional cost of updating the SHAs across all modules.
Instead we fork at-risk actions into the puppetlabs namespace and use them from there.
This allows us to consume updates at our pace and deploy changes across all modules without delay,
while avoiding actions that …

Update how we handle at-risk action sources

---

moduleroot/.github/workflows/pr_test.yml.erb

Prior to this PR, when the user submitting the PR was not the common
owner, the GitHub acceptance test setup would fail. The failure was because
there was a missing matrix due to an if statement. This PR generates
an empty matrix and skips acceptance tests if the matrix is empty.
Here was the error from when the common owner was not the repo owner. This was because the if/else bash did not run so the matrix was never set.
```
Error when evaluating 'strategy' for job 'Acceptance'. (Line: 80, Col: 15): Error reading JToken from JsonReader. Path '', line 0, position 0.,(Line: 80, Col: 15): Unexpected value ''
```
This fixes the issue where there is an empty matrix, which would have resulted in the following error.
```
Error when evaluating 'strategy' for job 'Acceptance'. (Line: 80, Col: …
```

(maint) Fix GitHub acceptance test setup when not common owner

---

config_defaults.yml

Prior to this change, if PUPPET_GEM_VERSION was not set, the system
Puppet Module Gems gem would not be installed, which would not have
installed Litmus. This was causing issues on CI pipelines as there
is a dependency on a helper script in Litmus during set up,
regardless as to whether PUPPET_GEM_VERSION is set or not.
This was introduced in the changes within #385 and #386.
With this change, we now ensure that the system PMG gem is installed
if PUPPET_GEM_VERSION is undefined.
This issue manifested on the `puppetlabs-apache` module.

(FIX) Ensure system PMG gem installed when PUPPET_GEM_VERSION nil

---

moduleroot/.github/workflows/nightly.yml.erb
moduleroot/.github/workflows/pr_test.yml.erb

The ruby/setup-ruby action is actually maintained by the Ruby people themselves. It has built in caching with the proper behavior. Not only is it easier to read (less syncing going on), it's also likely to be maintained properly. For example, to get proper caching of gems, bundle lock should run to get a Gemfile.lock which gives you a correct cache.  This action does it for you.
Note I didn't test it myself since I don't use PDK, but we've been using this in Voxpupuli (https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/.github/workflows/ci.yml.erb) and it works well in my experience. The only thing we don't currently do is to run on push as well. That means we don't have a shared cache ready and caches are now scoped to a user. It looks like pdk-templates is in the same …

Use ruby/setup-ruby Github action

---

object_templates/functions/function_spec.erb
object_templates/functions/native_function.erb
object_templates/functions/v4_function.erb

Previously pdk was not able to generate functions.  This adds the templates to do so.  This will need to merged before I can submit the PR in pdk to support functions.

Add object templates for functions

---

config_defaults.yml
moduleroot/Gemfile.erb

This has passed on https://github.com/puppetlabs/puppetlabs-powershell/pull/328 
I believe that the existing protections are enough for anything except `pdk --puppet-version=` and explicit CI setups with versions between 6.0 and 6.11, which are not versions that we support in [PE versions](https://puppet.com/docs/pe/2019.8/component_versions_in_recent_pe_releases.html).
Closes #391 , which is a different, more complex approach to this, which would also require changes to the PDK.
This also obsoletes https://github.com/puppetlabs/pdk/pull/935 for now.

Revert litmus protection

---

moduleroot/.github/workflows/auto_release.yml.erb

Addresses comments on PR: https://github.com/puppetlabs/pdk-templates/pull/393#pullrequestreview-583458528

Update Github Actions auto_release workflow

---

moduleroot/.gitlab-ci.yml.erb

Default before_script needs to be copied into the litmus test in order to do the `bundle install`

Needed before script to be copied into the before_script for litmus

---

config_defaults.yml

Since Ruby 3 didn't make this the new default, we don't have to inflict
this pain on our users either.

Don't enforce frozen string comments

---

README.md
config_defaults.yml

This changed addresses the missing removal of puppet 5 from default configuration highlighted in the comment: https://github.com/puppetlabs/pdk-templates/pull/403

Remove puppet5 from gitlab-ci defaults

---

moduleroot/.github/workflows/spec.yml.erb

This change adds a new workflow to run spec (unit) tests as a
standalone manual job and as options to the 'Nightly' and 'PR'
tests.

(IAC-1307) Add Spec tests to nightly and pr_test GHActions configs

---

moduleroot/.github/workflows/nightly.yml.erb
moduleroot/.github/workflows/pr_test.yml.erb

- Renaming the inventory.yaml file to litmus_inventory.yaml
- Relocating file from the module root directory to /spec/fixtures/
- Removal of vmpooler as it is deprecated
The point in this change is to avoid running tests on a live production system by accident.
This piece of work includes changes in multiple places. 
1. pdk-templates: https://github.com/puppetlabs/pdk-templates/pull/414
2. puppet_litmus: https://github.com/puppetlabs/puppet_litmus/pull/396
3. provision module: https://github.com/puppetlabs/provision/pull/161
The follow PR is testing out my changes: https://github.com/puppetlabs/puppetlabs-testing/pull/353

(GH-380) Relocation of inventory.yaml file

---

config_defaults.yml
moduleroot/.github/workflows/spec.yml.erb

Adds the static and syntax checks to the `config_defauly.yml` for
`.github/workflows/spec.yml`
Adds an additional step to the `Spec` workflow to run these checks.
Also corrects a typo in a previous step.
See https://github.com/puppetlabs/puppetlabs-testing/pull/354 for test output
Closes #417

Add static & syntax checks to spec workflow

---

moduleroot/Gemfile.erb

All platform-specific runtime dependencies are included by the PDK supported versions of Puppet, therefore these are no longer required.

(GH-419) Removal of win32 gems

---

config_defaults.yml

I think the new path for inventory(`/spec/fixtures/litmus_inventory.yaml`) should also be git-ignored by default, so we don't need to add manually in `.sync.yml` file for each supported module.

git ignore spec/fixtures/litmus_inventory.yaml

---

moduleroot/.github/workflows/release.yml.erb

Currently using nightlies causes failures on the pdk build step in our auto release process. 
Issue is being tracked here: https://tickets.puppetlabs.com/browse/PDK-1714

Revert to using pdk 2.1.0.0 rather than nightlies

---

moduleroot/.rubocop.yml.erb

"enabled_cops = cop_configs.key" is nil, if Hash is empty, so catch this case in an If-Clause.

Fix Bug in .rubocop.yml.erb

---

moduleroot/spec/spec_helper.rb.erb

This needs thorough review to make sure the patterns match what is not necessary in a PDK installed unit test.

Cleanup backtrace in spec tests

---

moduleroot/.github/workflows/release.yml.erb

We had tagged to pdk:2.1.0.0 due to: https://github.com/puppetlabs/pdk/issues/1075
This has now been resolved so rolling back to use the nightlies.

(maint) Use docker pdk:nightly container

---

README.md
moduleroot/Rakefile.erb

Allows setting the max_issues configuration for the github_changelog_generator tool to prevent Github API limitations for big repositories.

Add changelog_max_issues configuration

---

moduleroot/appveyor.yml.erb

If the owner of a repository creates a branch, pushes it, and then creates a PR, appveyor will not build it because of the branches filter (which is currently main & release).  This used to work but i'm guessing appveyor made a breaking change and this stopped at some point.

Set `skip_branch_with_pr` to true by default in appveyor.yml template

---

config_defaults.yml
moduleroot/.github/workflows/pr_test.yml.erb
moduleroot/.github/workflows/spec.yml.erb

puppetlabs_spec_helper provides a task called validate which runs all static checks (syntax, lint, etc). If these fail, there isn't really any reason why you would want to start a full matrix build. Similarly, it also runs Rubocop prior to the matrix. Otherwise you just get a full failed matrix. The end result is less wasted CI on invalid syntax or style.
This is taken from Voxpupuli's modulesync_config.
I know this is incomplete and personally I never use PDK, but it came up in https://github.com/puppetlabs/puppetlabs_spec_helper/pull/340.

Run validation steps prior to the matrix build

---

moduleroot/.github/workflows/auto_release.yml.erb

Prior to this PR, the auto release workflow would always result in a
commit and PR. This PR updates the logic to only make the PR if the
changelog is updated.
This reduces the noise from invalid releases during the release schedule by only making PR's when there are updates to the changelog. An example of this workflow run can be seen in https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector/runs/3124526271?check_suite_focus=true

Only auto release if the changelog is updated

---

config_defaults.yml
moduleroot/.rubocop.yml.erb

- Quoting the off hash key changed its value.
- enabled_cops conditional is always wrong because it isn't set yet
- hardcore should imply the kitchen sink, hence pending cops, too
- enabled cops is an array, not a hash.

(GH-327) Fix rubocop "off" & "hardcore" profiles

---

moduleroot/.gitlab-ci.yml.erb

Don't append a tag to image name if one already exists

---

moduleroot/.github/workflows/nightly.yml.erb
moduleroot/.github/workflows/pr_test.yml.erb
moduleroot/.github/workflows/spec.yml.erb

This PR resolves #448 by removing the empty `env` key from GitHub Actions templates if neither of the sub-keys are set. More details can be found on #448.

Remove env from GitHub template if all sub-keys are unset

---

moduleroot/.github/workflows/nightly.yml.erb

Although Github Actions are disabled on forks, a user can still manually enable them and encounter errors like that reported in [MODULES-11220](https://tickets.puppetlabs.com/browse/MODULES-11220).
This commit adds an `if` guard for the `Setup Test Matrix` and `slack-workflow-status` job and step, respectively

(MODULES-11220) Disable nightly workflows on forks

---

moduleroot/.github/workflows/spec.yml.erb

The puppetlabs/ruby_task_helper module provide helpers to write testable
bolt tasks.  For this to work, the tested module depends on a copy of the
ruby_task_helper module to be beside it: quoting ruby_task_helper's
documentation:
> Make sure the task helper repo is checked out next to your module so
> the relative requires work and you can write simple unit tests for the
> methods of your task.
This commit test for a `use_ruby_task_helper` setting to create a
symlink before running the test suite.  This link points to the fixture
directory where the appropriate version of ruby_task_helper will be
put according to what the `.fixtures.yml` file says in the module under
test.

Add a knob to allow tasks testing using ruby_task_helper

---

moduleroot/.rubocop.yml.erb

Prior to this commit the main template tested ruby syntax against ruby version 2.4
Since in the lowest Support release of Puppet, Ruby version 2.5 is in use, this is no longer the sensible default.
Defaulting to 2.5 ensures that code is linted to the most compatible ruby version for supported Puppet releases

Update TargetrubyVersion for rubocop

---

config_defaults.yml

This is a collection of puppet-lint plugins that reflect the current
community standards. Version 3 of the gem includes:
* puppet-lint-absolute_classname-check
* puppet-lint-anchor-check
* puppet-lint-classes_and_types_beginning_with_digits-check
* puppet-lint-file_ensure-check
* puppet-lint-leading_zero-check
* puppet-lint-legacy_facts-check
* puppet-lint-lookup_in_parameter-check
* puppet-lint-manifest_whitespace-check
* puppet-lint-optional_default-check
* puppet-lint-param-docs
* puppet-lint-params_empty_string-check
* puppet-lint-param-types
* puppet-lint-resource_reference_syntax
* puppet-lint-strict_indent-check
* puppet-lint-top_scope_facts-check
* puppet-lint-topscope-variable-check
* puppet-lint-trailing_comma-check
* puppet-lint-unquoted_string-check
* …

Use voxpupuli-puppet-lint-plugins

---

config_defaults.yml

Due to IAC being renamed to CAT the channel set here needs to be changed

(maint) Update default slack channel

---

moduleroot/.devcontainer/README.md

While #457 dealt with a deprecated setting, the README was left out. This PR solves that.

Update deprecated setting in README.md

---

object_templates/fact_spec.erb

Every time I create a fact I always forget how exactly to mock the data.  As a result I have added the helpful information here so that myself and others can easily see and use. 
This will be part of the unit test file anytime `pdk new fact <fact_name>` is run.

Adds documentation for testing and mocking facts

---

config_defaults.yml
moduleroot/Gemfile.erb

With the recent updates to bundler the need for a specific set off gems for each version of ruby that we support has been removed.
As such the logic behind our gems is now much simpler and can easily fit within the default templates, thus removing our need to have a separate module to manage them, with the templates already managing all other similar default requirements for our modules.

(CONT-19) Removal of puppet-module-gems

---

.travis.yml
config_defaults.yml

The Json version 2.6.2 causes issues for our Windows machines and so we are setting an exclusion against it.

(maint) Exclusion added against Json version

---

config_defaults.yml

We released Version 3.1 today. It pulls in latest versions of the different plugins. This is basically a bugfix because we noticed that pdk doesn't automatically update available gems. With this simple change, the version in the Gemfile will be raised and pdk will ensure latest versions are installed, without the requirement of people running `pdk bundle update` (which could have sideeffects).

voxpupuli-puppet-lint-plugins: Pull in 3.1 or newer

---

config_defaults.yml

Prior to this commit all modules have been consuming the JSON gem. This is causing issues with Windows Support. 
This change aims to resolve the issues and simplify gem and native extensions being used.

(MAINT) Replacing json with json_pure

---

config_defaults.yml

Json gems should be pinned to their default versions so that users aren't forced to recompile the native extensions.
See the following for a version matrix: https://stdgems.org/json/#gem-version

(CONT-422) - Re-pin json gems

---

README.md
moduleroot/spec/spec_helper.rb.erb

Reading [this article](https://dev.to/puppet/faster-module-tests-with-facter-4-and-rspec-puppet-561e) made me want to try the setting out. My CI job went from 5min40s to 2min37s so I was easily sold. This PR makes it possible to configure it through PDK templates.

allow to configure rspec-puppet's facter_implementation

---

moduleroot/.github/workflows/auto_release.yml.erb

Prior to this commit the PDK release image used was tagged with ci.
This commit updates the release prep container to use the latest version of the PDK.

(MAINT) Update pdk release image

---

moduleroot/.github/workflows/auto_release.yml.erb
moduleroot/.github/workflows/nightly.yml.erb
moduleroot/.github/workflows/pr_test.yml.erb
moduleroot/.github/workflows/release.yml.erb
moduleroot/.github/workflows/spec.yml.erb

This commit updates all instances of the actions/checkout@v2 to actions/checkout@v3 in perparation for the former's deprecation as part of the NodeJS deprecation.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

(maint) Updates checkout action

---

config_defaults.yml

This had previously been removed during the migration away from puppet_module_gems.
This commit re-adds the platform support for x64_mingw.

Add x64_mingw support for puppet_litmus

---

config_defaults.yml

This PR pins parallel_tests to 3.12.1 which is the last version that supports ruby 2.5.9.
The change is being implemented to prevent conflicts when building moduiles on older rubies.

(CONT-705) Pin parallel_tests gem

---

README.md
config_defaults.yml
moduleroot/Gemfile.erb

This change removes the template logic that adds
`puppet-lint_legacy_facts-checl` based on `common:disable_legacy_facts` config and fixes #501.
The legacy facts check is now part of puppet-lint which means including this gem is no longer required.
Additionally, users that currently have `disable_legacy_facts` set to `true` in their `.sync` file may encounter breaking dependency conflicts.

(GH-501) Remove legacy facts gem

---

config_defaults.yml

Those are required to ensure a certain level of coverage and it's the
current community best practice to have those reports enables. pdk
should reflect that.

Enable puppet coverage reports

---

config_defaults.yml

Prior to this PR, the path supplied to .gitignore for `spec/fixtures/modules/` did not allow for manual unsetting of .gitignore for subdirectories, which caused the check:gitignore check to fail and throw "File specified in .gitignore has been committed"
To give more context, take the puppetlabs-node_encrypt module. The node_encrypt module defines a module called "redact" within `spec/fixtures/modules/redact/`, and this is required for the testing of the module. However, once the `bundle exec rake syntax lint check:git_ignore` command is run, we get the error seen above.
This PR alters the required path added to the .gitignore of modules, but does not alter its core behaviour. (**it will still ignore all files under /spec/fixtures/modules**), however now we can pass additional paths to …

(maint) - Update fixtures/modules path for .gitignore

---

config_defaults.yml

Prior to this change we were seeing build failures with newer versions of racc because it needs to build native extensions.
This change pins racc for Ruby 2.7 to the version that is built in.

(MAINT) Pin racc for Ruby 2.7

---

moduleroot/Rakefile.erb

`Bundler.rubygems.find_name` will find gems in the PDK cache that are not currently included in the bundle, causing rake tasks to fail. `Gem.loaded_specs.key?` appears to be a better method of determining if a gem is present in the bundle. See #503, #513, and https://github.com/puppetlabs/pdk/issues/1256 for examples of the issue.

Update Rakefile gem detection method

---

README.md
moduleroot/spec/default_facts.yml.erb

This change allows the user to specify nested facts within their .sync.yml.
Before, if a user specified a networking fact in their .sync.yml with the below
```
spec/default_facts.yml:
extra_facts:
networking:
hostname: "kubernetes.localhost"
```
it would result in a duplicate key error in the default_facts.yml, like this:
```
networking:
ip: "172.16.254.254"
ip6: "FE80:0000:0000:0000:AAAA:AAAA:AAAA"
mac: "AA:AA:AA:AA:AA:AA"
is_pe: false
networking:
hostname: "kubernetes.localhost"
``` 
Now, when extra_facts is passed it will check for networking facts first, before clearing them and adding extra_facts as before.
A .sync.yml like below, will result in the following:
```
spec/default_facts.yml:
extra_facts:
networking:
hostname: "kubernetes.localhost"
domain: "localhost"
fqdn: …
```

(CONT-1229) - Allow nested extra networking facts

---

moduleroot/spec/spec_helper.rb.erb

Ruby does not have a native deep_merge function

(maint) - Opt for merge

---

.github/workflows/labeller.yml
README.md
config_defaults.yml
moduleroot/spec/default_facts.yml.erb
moduleroot/spec/spec_helper.rb.erb

This PR adds puppet-strings to the default template Gemfile.
Requires the following PR to be merged: https://github.com/puppetlabs/bolt/pull/3216
PDK is unable to pull in newer versions of puppet-strings because of a dependency in bolt. We should also reference puppet-strings as a first party gem in module Gemfiles.

(CONT-1119) Add puppet-strings

---

config_defaults.yml

Prerequisite:
Requires a new release of bolt containing this change https://github.com/puppetlabs/bolt/pull/3216.

(maint) - bump puppet-strings to ~> 4.0

---

moduleroot/Rakefile.erb

Allow puppet-lint fail_on_warnings to be disabled

---

config_defaults.yml

Request coming in through community wants the modules build to ignore the github directory as it adds to the build size of each module.

[CAT-1541] : Adding github directory to pdkignore

---

config_defaults.yml

We have multiple use cases where we are installing all gems every time which also lead to installing old gems or conflicts, so creating `release_prep` for releasing the module.

(CAT-1606) - Adding gem group for release_pre

---

config_defaults.yml

Updating `puppetlabs_spec_helper-version` gem version.

(MAINT) - Updating puppetlabs_spec_helper gem version to latest

---

config_defaults.yml

(CAT-1612) Revert removal of puppetlabs_spec_helper and puppet-string changes

---

README.md

Documents new `manage_execute_permissions` setting as added in https://github.com/puppetlabs/pdk/pull/1289
https://github.com/puppetlabs/pdk/issues/1224
https://github.com/puppetlabs/pdk/pull/1289

Add documentation for manage_execute_permissions setting

---

Gemfile
config_defaults.yml
moduleroot/.rubocop.yml.erb
rubocop/defaults-1.50.0.yml

Following a recent team decision, we are implementing a Rubocop Upgrade, moving the version from 1.48.1 to 1.50.0. This should be the final version until Puppet 7 is unsupported. This change should help any module dependant on PDK to easily update.

(CAT-1686) Upgrade Rubocop 1.48.1 to 1.50.0

---

moduleroot/.rubocop.yml.erb

This had previously been manually added to the Modules, however adding it here to ensure that it stayed in place had been missed.

(BUGFIX) Enable NewCops by default

---

Gemfile
config_defaults.yml

Following the completion of CAT-1686, it was noticed that pdk-templates was assigned the wrong expectation, asserting a static (=) version instead of a pessimistic expectation (~).
This PR aims to fix this.

(CAT-1688) - Pin rubocop to `~> 1.50.0`

---

config_defaults.yml

the codecov gem is deprecated, and no longer required in
puppetlabs_spec_helper. We should remove this from the pdk-templates
configu defaults, as it has stopped receiving updates and is restricting
us on the versions of simplecov we can consume.

(CAT-1693) - Remove deprecated codecov gem

---

README.md
moduleroot/Gemfile.erb

Useful for testing changes to default gems. I'm using this to test puppet_litmus changes.
Currently there is no way to override default gems other than forking the pdk-templates repo.

allow overriding default gems

---

moduleroot/.rubocop.yml.erb

This commit initially was created as a way to be able to automate a large chunk of work regarding Rubocop file amends, during our Puppet 8 work back in April 2023. However, once such work was performed, this fix was no longer needed and it, effectively, introduced a bug where cop rules cannot be configured via sync.yml if they have been actively set to enabled here.
This commit aims to address the current bug by reverting the previous change.
Reverts puppetlabs/pdk-templates#554

Revert "(BUGFIX) Enable NewCops by default"

---

moduleroot/.rubocop.yml.erb

Upon further testing, it was concurred that removing this feature did not fix the current problem. Therefore, we are undoing the revert.
Reverts puppetlabs/pdk-templates#566

Re-implement "(BUGFIX) Enable NewCops by default"

---

.ci/fixtures/new_provider_sync.yml
.ci/test_script.sh
moduleroot/.rubocop.yml.erb

Prior to this commit, it was noticed that Rubocop rules that were set to false in .sync.yml would not be properly overriden if the cop already existed as a default enabled cop.
This commit aims to correct this unintended functionality and adds a test case.

(CAT-1743) Address .sync.yml not overriding cops

---

config_defaults.yml

Duplicate gems within the Gemfile our causing issue with the PDK, this aims to resolve this by removing the duplicates and instead creating a joint `:development, :release_prep` group for the gems that overlap between them, rather than having them repeated in both groups seperately.

(CAT-1754) Remove duplicate gems

---

config_defaults.yml

We're using this since some time at Vox Pupuli and I think Puppet should also use the latest version of their own software. Tested for development group in https://github.com/puppetlabs/puppetlabs-apt/blob/main/Gemfile#L26

puppetlabs_spec_helper: Require 7.X

---

config_defaults.yml

When using PDK with a Bolt project it's usually expected to ignore some more files.
```yaml
- '.resource_types'
- '.modules'
- '.task_cache.json'
- '.plan_cache.json'
- '.rerun.json'
- 'bolt-debug.log'
- 'Puppetfile'
```

Add bolt-related files to .gitignore default paths

---

config_defaults.yml
moduleroot/.rspec.erb

This PR removes the .rspec.erb file from the pdk-templates, and thus the .rspec file from being managed by PDK. This was made possible due to the changes found in https://github.com/puppetlabs/puppetlabs_spec_helper/pull/452.
This has minimal impact on users as the file was not configurable through .sync.yml before (other than to set as unmanaged), for existing modules with the .rspec it will not be removed and new modules created will simply not include the file.
https://github.com/puppetlabs/puppetlabs_spec_helper/pull/452.

(CAT-1868) - Remove .rspec.erb

---

config_defaults.yml

See issue below:
https://github.com/ruby/rexml/issues/131

(CAT-1871) Pin `rexml` due to issues on Windows

---

config_defaults.yml

This pull request removes the pinned version of rexml as it is no longer need as the latest release resolves the issue with rexml gem on windows 
https://github.com/puppetlabs/pdk-templates/compare/cat_1887?expand=1

(CAT-1887) - remove pinned version of rexml

---

config_defaults.yml

Reverts puppetlabs/pdk-templates#592
Reverting as it looks like the issues are still occurring.
Problem nature of PR seems to have been hidden by the exact way in which the test builds are run.

Revert "(CAT-1887) - remove pinned version of rexml"

---

.gitignore
config_defaults.yml

In many projects it's common to install gems into .vendor/, not vendor/. people tend to copy and paste commands from their history. I think it makes sense to add it to the .gitignore here as well.

.gitignore: Add /.vendor/

---

config_defaults.yml

Module build rake tasks are scheduled for removal in `puppetlabs_spec_helper v8`. `puppet-blacksmith` offers a range of rake tasks, and was already included in `puppetlabs_spec_helper` as a soft dependency, so we should avail of these instead of producing duplicate logic and rake tasks.
This adds the puppet-blacksmith gem to the pdk-templates, and bumps puppetlabs_spec_helper to v8.
https://github.com/puppetlabs/puppetlabs_spec_helper/pull/472

(CAT-2056) - add puppet-blacksmith to templates

---

config_defaults.yml

Update the configuration of lint with the templates to match that of the puppetlabs_spec_helper to ensure compliance between the PDK lint runs and the Rake lint runs.
Due to how the templates work, `Rakefile` configurations are inherited by the `.puppet-lint.rc`

(CAT-2010) Update lint configuration to match puppetlabs_spec_helper

---

config_defaults.yml

PDK build step is currently failing on Windows with regards to Ruby 2 due to a conflict with the gem bigdecimal which has been brought in by json-schema 5.1.1

(BUGFIX) Pin json-schema below 5.1.1 to resolve issues with Ruby 2 on Windows

---

config_defaults.yml

Update facterdb from 1.x to 3.x and update rspec-puppet-facts from 3.x to 5.x.
Upstream facterdb and rspec-puppet-facts have removed support for legacy facts, which is useful for testing for Puppet 8.
See https://github.com/voxpupuli/facterdb/blob/master/CHANGELOG.md and https://github.com/voxpupuli/rspec-puppet-facts/blob/master/CHANGELOG.md for more details.
N/A

Update facterdb to 3.x and rspec-puppet-facts to 5.x

---

moduleroot/Gemfile.erb

Since the `PUPPET_GEM_VERSION` and `FACTER_GEM_VERSION` are not always going to be version contraints (they can also be a git URL), then I'm removing this flexible check and pinning only to the latest puppetcore gems.  If flexible puppet and facter gemsources are need via https or git, then remove the PUPPET_FORGE_TOKEN and use PUPPET_GEM_VERSION and/or FACTER_GEM_VERSION instead.

Only pin to the puppetcore versions.

---

.ci/install_pdk.sh

The Puppet GPG key (D6811ED3ADEEB8441AF5AA8F4528B6CD9E61EF26) expired on April 6, 2025, causing CI failures with the error:
```bash
W: GPG error: [http://apt.puppet.com](http://apt.puppet.com) noble InRelease:
The following signatures were invalid: EXPKEYSIG 4528B6CD9E61EF26
Puppet, Inc. Release Key (Puppet, Inc. Release Key) <release@puppet.com>
```
This commit adds a step to fetch the non-expiring version of the same key <https://apt.puppetlabs.com/DEB-GPG-KEY-future> ensuring the CI pipeline can validate the repository signature.
This PR modifies the `.ci/install_pdk.sh`  to 
* Fetch and add the non-expiring version of the same key
* Install the pdk package as before.
- Verified that the key ID from DEB-GPG-KEY-future matches the expired key ID
- Confirmed this modification fixes the …

(CAT-2283) Fix CI failures by using non-expiring Puppet GPG key

---

config_defaults.yml
moduleroot/.rubocop.yml.erb

With the EOL of Puppet 7, we no longer need to support Ruby < 3.1.

(CAT-2286) Remove Ruby < 3.1 dependencies

---

config_defaults.yml

Updates the puppet debugger version to reflect new changes with the debugger and default fact set.

Update default puppet-debugger version

---

config_defaults.yml
moduleroot/.rubocop.yml.erb

Updating puppet_litmus to bring in changes to `matrix_from_metadata_v2` that point the tests towards the new puppetcore versions.

(CAT-2357) Update puppet_litmus pin to test against puppetcore

---

docs/testing-pdk-module-gemfile-sources.md
moduleroot/Gemfile.erb

This PR introduces a significantly enhanced Gemfile.erb for that provides flexible, multi-source gem management capabilities for all pdk modules. The new system addresses development and deployment challenges by supporting multiple gem sources, environment-driven configuration, and comprehensive testing scenarios.
* **Environment-Driven Configuration**.  The new Gemfile uses environment variables (`GEM_SOURCE` and `GEM_SOURCE_PUPPETCORE`) to configure gem sources, enabling the same file to work across multiple gem sources.
* **Improved `location_for` method** handles not only unique puppet and facter sources (git, https, file:, etc) but also different gemsources too.  For example, at the same time as pull facter from artifactory or rubygems-puppetcore, you can setup puppet to source from …

(CAT-2416) Enhance PDK Gemfile Template to Support Flexible Source Testing

---

moduleroot/Gemfile.erb

This PR restores backward compatibility for the `PUPPET_FORGE_TOKEN` environment variable by re-introducing its automatic switching behavior for puppetcore gem sourcing in PDK module Gemfiles.
In previous PDK template versions, setting `PUPPET_FORGE_TOKEN` would automatically configure the Gemfile to source `puppet` and `facter` gems from the puppetcore gem repository (`https://rubygems-puppetcore.puppet.com`). This behavior was removed in recent template changes, breaking existing workflows that relied on this automatic switching.
This change restores the backward compatibility by:
- **Re-introducing the PUPPET_FORGE_TOKEN switch logic**: When `PUPPET_FORGE_TOKEN` is present, the Gemfile automatically sets `GEM_SOURCE_PUPPETCORE` to `https://rubygems-puppetcore.puppet.com`
- …

(CAT-2431) Restore PUPPET_FORGE_TOKEN backward compatibility for puppetcore gem sourcing
