- README.md
Current usage in the README is incorrect.
> Updating README with template url usage

- moduleroot/.rubocop.yml.erb
This fixes https://github.com/puppetlabs/pdk/issues/420
> Succeed with unsupported rubocop versions

- README.md
- config_defaults.yml
- moduleroot/spec/default_facts.yml.erb
> Customization of default_facts.yml

- config_defaults.yml
- moduleroot/.gitlab-ci.yml.erb
Prior to this PR we created a pipeline that looked like: 
This PR creates a pipeline that looks like this:
> (PDK-981) Make .gitlab-ci look like .travis

- moduleroot_init/README.md.erb
And some editorial tidying up along the way.
> deprecating README Reference section

- .travis.yml
- .travis/test_script.sh
See an example of what it looks like here: 
https://travis-ci.com/npwalker/pdk-templates/builds/73507717
> Add travis testing to ensure template changes work

- moduleroot/Rakefile.erb
Only run the changelog helpeer functions if we are running the changelog task
> (PDK-1044) changelog functions if changelog task

- README.md
- config_defaults.yml
- moduleroot/.travis.yml.erb
This allows one to set the BEAKER_TESTMODE variable using the .sync file.  if no value is set then a default of `apply` is used
> add ability to support BEAKER_TESTMODE

- README.md
- moduleroot/.gitlab-ci.yml.erb
support custom rubygems mirror url
> Rubygems mirror

- moduleroot_init/README.md.erb
> Whitespace fixes in README.erb.md

- README.md
The README.md had bunder_args instead of bundler_args. This PR fixes that.
> Changes bunder to bundler in README.md

- README.md
- config_defaults.yml
Removing uninformative comments being used as version control.
> Remove commented out data

- config_defaults.yml
- moduleroot/Rakefile.erb
also alphabetising lists in config_defaults for easier reading
> (FM-7847) adding puppet_litmus defaults

- README.md
- moduleroot/.travis.yml.erb
> (GH-221) Make .travis.yml's dist attribute configurable

- .travis/test_script.sh
Hopefully this will successfully branch at the right commit for both
pull requests and pushes to master.
> (MAINT) --template-ref commit targetting again

- README.md
- moduleroot/spec/spec_helper.rb.erb
Request for review 
Add hiera_execute_config to accept any commands to specify in the spec_helper.rb file
> (PDK-1355) Add hiera_config_ruby to accept ruby snippets

- object_templates/transport.erb
- object_templates/transport_spec.erb
- object_templates/transport_type.erb
- object_templates/transport_type_spec.erb
Implementation for https://github.com/puppetlabs/pdk-planning/pull/31
> (FM-8081) Templates for `pdk new transport`

- object_templates/transport_spec.erb
- object_templates/transport_type_spec.erb
with those changes the acceptance tests in the PDK pass on my machine.
> (FM-8081) fix up last issues in transport template

- moduleroot/.vscode/extensions.json
This commit adds a VSCode recommended extensions file to the project.
When a user opens up a module managed by the PDK with VSCode, they will
be presented with a popup notification recommending these extensions.
The user can choose to ignore the recommendations or install all or just
one of the extensions.
> (maint) VSCode Recommended Extensions file

- .travis/install_pdk.sh
- config_defaults.yml
Long term this dependency should be a default gem in the PDK runtimes.
> (maint) Add rb-readline to Windows gems

- README.md
- moduleroot/.travis.yml.erb
- moduleroot/appveyor.yml.erb
> Support setting `os` and `install` keys for appveyor and travis

- moduleroot/Rakefile.erb
- moduleroot/spec/spec_helper.rb.erb
- object_templates/class_spec.erb
- object_templates/defined_type_spec.erb
- object_templates/provider.erb
- object_templates/provider_spec.erb
- object_templates/provider_type.erb
- object_templates/provider_type_spec.erb
- object_templates/transport.erb
- object_templates/transport_device.erb
- object_templates/transport_spec.erb
- object_templates/transport_type.erb
- object_templates/transport_type_spec.erb
- rubocop/profile_builder.rb
This PR is a PoC for #304
I would be glad to receive feedback.
> Add header to *.rb files to be ruby 2.4+ compatible

- README.md
> (#292) Document the 'required' parameter for .gitignore and .pdkignore templates

- moduleroot/.vscode/extensions.json
This commit update the ID of the Puppet VS Code extenion in the
extensions.json file. Modules that update after this commit will receive
recommendations to install the new extension.
> (maint) Update Puppet VS Code Extension publisher

- moduleroot_init/README.md.erb
Even if some parts of the ```README.md``` are modified or removed by the user, they should pass the validation of ```markdownlint```. 
* https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
> Validate README.md via markdownlint

- moduleroot/.travis.yml.erb
> use --targets instead of --nodes for bolt command

- moduleroot/.travis.yml.erb
> (maint) Ensure wget install succeeds on RHEL OSs

- moduleroot/.devcontainer/Dockerfile
- moduleroot/.devcontainer/devcontainer.json
> (#348) Add .devcontainer for vscode

- moduleroot/spec/spec_helper.rb.erb
Fix previous change where false value would not work because of conditional.
> Conditional can't be used with false. Since default is true it is not needed

- config_defaults.yml
> (#352) Add .puppet-lint.rc and .sync.yml to .pdkignore

- moduleroot_init/.sync.yml.erb
> (#353) Add an empty, commented .sync.yml

- README.md
This is a rebase and conflict resolution from https://github.com/puppetlabs/pdk-templates/pull/281 by @scotje. All mistakes and errors mine.
Co-Authored-By: Jesse Scott <jesse@puppetlabs.com>
> (MAINT) Fix README typos

- object_templates/fact.erb
- object_templates/fact_spec.erb
* previously pdk did not support creating facts.  If my feature is merged 
iI will need these object templates to support generating
facts and fact test files.
> Add object templates for generating new facts

- .travis/test_script.sh
- README.md
Removal of any inappropriate or offensive terminology from the code base.
> (IAC-1026) - Removal of Inappropriate Terminology

- moduleroot/Rakefile.erb
Closes #139 
While I do not fully understand the reasons for the failures as seen in the ticket, adding the require seems innocuous enough. My best guess is that there is rvm or similar interfering in the user's environment confusing something.
> Add bundler require to Rakefile

- README.md
- config_defaults.yml
- moduleroot/.gitlab-ci.yml.erb
> Gitlab litmus

- moduleroot/.gitlab-ci.yml.erb
Fix issue where litmus variables was necessary and should have been optional.
> Make litmus[variables] optional

- .travis/test_script.sh
- config_defaults.yml
- object_templates/fact.erb
- object_templates/fact_spec.erb
- object_templates/functions/function_spec.erb
- object_templates/functions/native_function.erb
- object_templates/functions/v4_function.erb
- object_templates/transport_device.erb
* add frozen string comments
* whitespace fixes
* remove obsolete rubocop disabling
* improve test script to catch regressions
Fixes #397
> (#397) Address some validation issues in object_templates

- .travis/test_script.sh
- object_templates/transport_device.erb
* change test data to trigger the necessity for this
* change template to only include this if necessary
> Re-add ClassAndModuleCamelCase disabling on transport_device

- moduleroot/.github/workflows/auto_release.yml.erb
Updating based on feedback from @ekohl on the apache PR. 
https://github.com/puppetlabs/puppetlabs-apache/pull/2125
> (maint) Updating version and owner in release workflow

- moduleroot/.github/workflows/nightly.yml.erb
- moduleroot/.github/workflows/pr_test.yml.erb
Depends on https://github.com/puppetlabs/puppet_litmus/pull/385
> Use different providers in Github Action workflows matrix

- config_defaults.yml
> (#412) Add .devcontainer to .pdkignore

- config_defaults.yml
We don't want to force these processes on everyone
> Fix defaults for .github/workflows/release.yml

- moduleroot/.github/workflows/auto_release.yml.erb
Example PR: https://github.com/puppetlabs/puppetlabs-testing/pull/358
> Add a check list for reviewers before merging a release prep

- .travis/install_pdk.sh
- Gemfile
- config_defaults.yml
- rubocop/defaults-1.6.1.yml
- rubocop/profile_builder.rb
* Clean up per YAMLlint
* Clean up per RuboCop
* Use `bash` for `.travis/install_pdk.sh` b/c POSIX `sh` does not include `local`, but `bash` does
> Misc cleanup

- README.md
- moduleroot/.github/workflows/auto_release.yml.erb
Allow users to set custom release schedule cron configuration
> Allow auto_release workflow schedule configuration

- README.md
- config_defaults.yml
- moduleroot/.travis.yml.erb
This PR re-adds files that were incorrectly removed during the removal of travis from our CI.
> (maint) - Add travis

- moduleroot/spec/spec_helper.rb.erb
The missing single quotes cause an error when used in PDK
Fixes https://github.com/puppetlabs/pdk/issues/1238
> Add missing quotes around facter_implementation

- README.md
- config_defaults.yml
- moduleroot/spec/default_facts.yml.erb
> (maint) - replace legacy facts in config_defaults.yml

- moduleroot/spec/default_facts.yml.erb
- moduleroot/spec/spec_helper.rb.erb
> Maint final fact fixes

- moduleroot/Rakefile.erb
Cleanup activity - Removing the reference of github changelog.
> (MAINT) - Remove github_changelog gem footprint

- moduleroot/.github/workflows/release.yml.erb
Very minor change, removes extra whitespace present in the release action template.
> Remove whitespace

- .github/workflows/release_prep.yml
> (CAT-1684) Addition of CHANGELOG.md

- CHANGELOG.md
Workflow will not trigger correctly if no changelog is present
> (CAT1684) Add blank CHANGELOG.md

- .github/workflows/release_prep.yml
Previously removed as thought it was relevant only to the metadata, however testing showed that it was relevant to the cmmit/PR title as well.
> (CAT-1684) Re-add section to workflow

- config_defaults.yml
> metadata-json-lint: Switch to 4.x

- config_defaults.yml
> (CAT-1739) Pin `CFPropertyList` to resolve dependency brought in by Bolt

- config_defaults.yml
> (CAT-1739) Restrict CFPropertyList pin to Windows

- config_defaults.yml
> config_defaults.yml: Cleanup trailing whitespace

- README.md
Smal amount of syntax fixes to the README.md
> (MAIT) Readme syntax fixes

- config_defaults.yml
Older versions had a broken factset for Debian 12.
> facterdb: Require 1.26 or newer

- config_defaults.yml
- moduleroot/.rspec.erb
Reverts puppetlabs/pdk-templates#581
> Revert "(CAT-1868) - Remove .rspec.erb"

- config_defaults.yml
Update pin to match what is being brought in elsewhere.
> (BUGFIX) Pin deep_merge to `~> 1.2.2`

- moduleroot/Gemfile.erb
Latest version of puppetcore facter is 4.11 now so updating
> Update to latest puppetcore facter.
